language: r
cache: packages
pandoc_version: 1.19.2.1

before_script:
  - chmod +x ./_bookdown_files/_build.sh
  - chmod +x ._bookdown_files/_deploy.sh

script:
  - ./_bookdown_files/_build.sh
  - ./_bookdown_files/_deploy.sh
